# Pima indians diabetes dataset analysis using SVM Classification Technique

In [1]:
#import library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn

In [2]:
df = pd.read_csv('pima-indians-diabetes.csv')

In [3]:
df

,Pregnancies,Glucose\n,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigree\n,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
df.head(20)

,Pregnancies,Glucose\n,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigree\n,Age,Class
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
5,5,116,74,0,0,25.6,0.201,30,0
6,3,78,50,32,88,31.0,0.248,26,1
7,10,115,0,0,0,35.3,0.134,29,0
8,2,197,70,45,543,30.5,0.158,53,1
9,8,125,96,0,0,0.0,0.232,54,1
10,4,110,92,0,0,37.6,0.191,30,0
11,10,168,74,0,0,38.0,0.537,34,1
12,10,139,80,0,0,27.1,1.441,57,0
13,1,189,60,23,846,30.1,0.398,59,1
14,5,166,72,19,175,25.8,0.587,51,1
15,7,100,0,0,0,30.0,0.484,32,1
16,0,118,84,47,230,45.8,0.551,31,1
17,7,107,74,0,0,29.6,0.254,31,1
18,1,103,30,38,83,43.3,0.183,33,0
19,1,115,70,30,96,34.6,0.529,32,1

In [5]:
#Check the weather any null value present here or not  
df.isnull().sum()

Pregnancies           0
Glucose\n             0
BloodPressure         0
SkinThickness         0
Insulin               0
BMI                   0
DiabetesPedigree\n    0
Age                   0
Class                 0
dtype: int64

In [6]:
#Drop the Label value from this data_set
x = df.drop(['Class'],axis =1 )

In [7]:
x

,Pregnancies,Glucose\n,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigree\n,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [8]:
# Separated Label Value 
y = df['Class']

In [9]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Class, Length: 768, dtype: int64

# Train Data

In [10]:
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC

In [11]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size = .20,random_state = 1)

In [12]:
xtrain

,Pregnancies,Glucose\n,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigree\n,Age
663,9,145,80,46,130,37.9,0.637,40
712,10,129,62,36,0,41.2,0.441,38
161,7,102,74,40,105,37.2,0.204,45
509,8,120,78,0,0,25.0,0.409,64
305,2,120,76,37,105,39.7,0.215,29
...,...,...,...,...,...,...,...,...
645,2,157,74,35,440,39.4,0.134,30
715,7,187,50,33,392,33.9,0.826,34
72,13,126,90,0,0,43.4,0.583,42
235,4,171,72,0,0,43.6,0.479,26
37,9,102,76,37,0,32.9,0.665,46

In [13]:
model = SVC()

In [14]:
model.fit(xtrain,ytrain)

SVC()

# Test Score

In [15]:
model.score(xtest,ytest)

0.7857142857142857

In [ ]:
# This model gave 78% acurate answer by using SVM CLassification Technique.